server:
  port: 80

# 默认值为 classpath:/META-INF/resources/,classpath:/resources/,classpath:/public/
spring:
  resources:
    static-locations: classpath:/META-INF/,classpath:/static/

conf:
  defaultRootPath: C:/Users/liu49/Pictures/
  thumbnailPath: G:/WorkSpace/thumbnail/
  thumbnailImageSize: 400.0
