server:
  port: 80

# 默认值为 classpath:/META-INF/resources/,classpath:/resources/,classpath:/public/
spring:
  resources:
    static-locations: classpath:/META-INF/,classpath:/static/

settle:
  conf:
    thumbnailImageSize: 400.0

---
spring:
  profiles: fankux

settle:
  conf:
    defaultRootPath: E:/a1r/
    thumbnailPath: E:/thumbnail/

---
spring:
  profiles: llzzll

settle:
  conf:
    defaultRootPath: C:/Users/liu49/Pictures/
    thumbnailPath: G:/WorkSpace/thumbnail/