# 通用配置
server:
  port: 80

# 默认值为 classpath:/META-INF/resources/,classpath:/resources/,classpath:/public/
spring:
  resources:
    static-locations: classpath:/META-INF/,classpath:/static/

mybatis:
  config-locations: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fl.entity
  type-handlers-package: com.fl.dao

logging:
  level:
    root: info

settle:
  conf:
    thumbnailImageSize: 400.0


#分profile配置
---
spring:
  profiles: fankux

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:C:/Users/Fankux/Desktop/settle/store/store.db
    username: root
    password: fast

settle:
  conf:
    defaultRootPath: E:/Pictures/Hash
    thumbnailPath: E:/thumbnail/
    libPath: C:/Users/Fankux/Desktop/settle/lib

---
spring:
  profiles: llzzll

datasource:
  driver-class-name: org.sqlite.JDBC
  url: jdbc:sqlite:/Users/fl/dev/settle/store.db
  username: root
  password: fast

settle:
  conf:
    defaultRootPath: C:/Users/liu49/Pictures/
    thumbnailPath: G:/WorkSpace/thumbnail/
    libPath: C:/Users/Fankux/Desktop/settle/lib
